# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.0

LABEL MAINTAINER="kartik"

# EXPOSE 8080

# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY wars/ /usr/local/tomcat/webapps/