global:
  resolve_timeout: 1m

route:
  group_by: [alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: <your-email>@gmail.com
    from: <your-email>@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: <your-email>@gmail.com
    auth_identity: <your-email>@gmail.com
    auth_password: kuzoscnlkrfouclg




# route:
#   group_by: ['alertname']
#   group_wait: 10s
#   group_interval: 10s
#   repeat_interval: 1h
#   receiver: 'web.hook'
# receivers:
# - name: 'web.hook'
#   webhook_configs:
#   - url: 'http://127.0.0.1:5001/'
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']

